"""Auto-generated migration

Revision ID: 014591936c07
Revises: 447c61b0aec7
Create Date: 2025-08-22 23:43:58.978506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014591936c07'
down_revision = '447c61b0aec7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 