"""Auto-generated migration

Revision ID: 06ae0a2719a5
Revises: 43dce731f63e
Create Date: 2025-08-22 23:42:52.247239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ae0a2719a5'
down_revision = '43dce731f63e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 