"""Auto-generated migration

Revision ID: 0954521d3a6f
Revises: 2d5bdedc86f2
Create Date: 2026-07-08 12:31:21.302180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0954521d3a6f'
down_revision = '2d5bdedc86f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 