"""Auto-generated migration

Revision ID: 0a1ea4a4d75e
Revises: bf010058b9bd
Create Date: 2025-08-23 00:19:11.318248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1ea4a4d75e'
down_revision = 'bf010058b9bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 