"""Auto-generated migration

Revision ID: 0b6aa424b986
Revises: 6d16432d0d67
Create Date: 2025-07-15 00:50:07.239123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6aa424b986'
down_revision = '6d16432d0d67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 