"""Auto-generated migration

Revision ID: 201adda7d846
Revises: 7e823c9c69e7
Create Date: 2026-05-01 18:22:21.132518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201adda7d846'
down_revision = '7e823c9c69e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 