"""Auto-generated migration

Revision ID: 242214557367
Revises: 2c748d8ab302
Create Date: 2025-08-22 18:28:50.765840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242214557367'
down_revision = '2c748d8ab302'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 