"""Auto-generated migration

Revision ID: 2c748d8ab302
Revises: 774f1da2cf20
Create Date: 2025-08-22 18:28:37.616363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c748d8ab302'
down_revision = '774f1da2cf20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 