"""Auto-generated migration

Revision ID: 2d5bdedc86f2
Revises: 4478d8173a64
Create Date: 2026-07-06 14:35:41.893009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5bdedc86f2'
down_revision = '4478d8173a64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 