"""Auto-generated migration

Revision ID: 348d5245e1e7
Revises: 7c3866a81820
Create Date: 2026-02-21 15:10:02.072280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348d5245e1e7'
down_revision = '7c3866a81820'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 