"""Auto-generated migration

Revision ID: 35b3567319e9
Revises: 0954521d3a6f
Create Date: 2026-08-19 14:43:44.338195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b3567319e9'
down_revision = '0954521d3a6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 