"""Auto-generated migration

Revision ID: 3667e09d6df8
Revises: f9a994aa16c3
Create Date: 2025-08-22 19:23:36.891867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3667e09d6df8'
down_revision = 'f9a994aa16c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 