"""Auto-generated migration

Revision ID: 3c03eac7ba3f
Revises: 67d0a0a0723d
Create Date: 2025-08-23 20:47:19.871481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c03eac7ba3f'
down_revision = '67d0a0a0723d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 