"""Auto-generated migration

Revision ID: 400e791a49f8
Revises: 713d4ce1e9e0
Create Date: 2025-07-15 00:39:29.494493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400e791a49f8'
down_revision = '713d4ce1e9e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 