"""Auto-generated migration

Revision ID: 405e9db70e61
Revises: d11e80d5b324
Create Date: 2025-08-26 16:54:46.197259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405e9db70e61'
down_revision = 'd11e80d5b324'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 