"""Auto-generated migration

Revision ID: 43dce731f63e
Revises: bfe0ab6f0229
Create Date: 2025-08-22 23:42:39.244845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43dce731f63e'
down_revision = 'bfe0ab6f0229'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 