"""Auto-generated migration

Revision ID: 4478d8173a64
Revises: e3aabb037243
Create Date: 2026-07-06 13:16:16.354113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4478d8173a64'
down_revision = 'e3aabb037243'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 