"""Auto-generated migration

Revision ID: 447c61b0aec7
Revises: 65f5b1aaae66
Create Date: 2025-08-22 23:43:45.500436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447c61b0aec7'
down_revision = '65f5b1aaae66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 