"""Auto-generated migration

Revision ID: 4dd8c0d0e3ac
Revises: c26b30a44bbe
Create Date: 2025-08-22 18:27:57.880983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd8c0d0e3ac'
down_revision = 'c26b30a44bbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 