"""Auto-generated migration

Revision ID: 4e8f157cbd32
Revises: b1c6dc01ebb2
Create Date: 2025-08-25 17:27:18.123239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8f157cbd32'
down_revision = 'b1c6dc01ebb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 