"""Auto-generated migration

Revision ID: 4fc870f689e8
Revises: 4e8f157cbd32
Create Date: 2025-08-26 12:14:08.429194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc870f689e8'
down_revision = '4e8f157cbd32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 