"""Auto-generated migration

Revision ID: 5299a866852e
Revises: a19536f5ee80
Create Date: 2026-06-16 13:47:27.246346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5299a866852e'
down_revision = 'a19536f5ee80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 