"""Auto-generated migration

Revision ID: 52b449cbc56e
Revises: 201adda7d846
Create Date: 2026-05-04 15:51:40.281878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b449cbc56e'
down_revision = '201adda7d846'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 