"""Auto-generated migration

Revision ID: 5346d030f3c5
Revises: eb03d573f874
Create Date: 2026-02-28 15:50:21.222449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5346d030f3c5'
down_revision = 'eb03d573f874'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 