"""Auto-generated migration

Revision ID: 54fcc0ae556e
Revises: c089b1db81c6
Create Date: 2025-07-17 21:06:31.472031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fcc0ae556e'
down_revision = 'c089b1db81c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 