"""Auto-generated migration

Revision ID: 569d6a12589b
Revises: eed040329fc8
Create Date: 2026-03-04 21:49:51.751552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569d6a12589b'
down_revision = 'eed040329fc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 