"""Auto-generated migration

Revision ID: 59bd1fa882b3
Revises: e71f57311002
Create Date: 2025-08-23 00:20:29.810163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bd1fa882b3'
down_revision = 'e71f57311002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 