"""Auto-generated migration

Revision ID: 5b949d1fd354
Revises: 3c03eac7ba3f
Create Date: 2025-08-23 23:31:26.377363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b949d1fd354'
down_revision = '3c03eac7ba3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 