"""Auto-generated migration

Revision ID: 65f5b1aaae66
Revises: 6cc2a1ca59bf
Create Date: 2025-08-22 23:43:31.631282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f5b1aaae66'
down_revision = '6cc2a1ca59bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 