"""Auto-generated migration

Revision ID: 67d0a0a0723d
Revises: c5bf54a6039d
Create Date: 2025-08-23 00:26:34.369648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d0a0a0723d'
down_revision = 'c5bf54a6039d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 