"""Auto-generated migration

Revision ID: 6cc2a1ca59bf
Revises: d39f83a72b51
Create Date: 2025-08-22 23:43:18.463592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc2a1ca59bf'
down_revision = 'd39f83a72b51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 