"""Auto-generated migration

Revision ID: 6d16432d0d67
Revises: 400e791a49f8
Create Date: 2025-07-15 00:41:50.552363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d16432d0d67'
down_revision = '400e791a49f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 