"""Auto-generated migration

Revision ID: 713d4ce1e9e0
Revises: 8e65e4094633
Create Date: 2025-07-15 00:21:55.801372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713d4ce1e9e0'
down_revision = '8e65e4094633'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('note', sa.String(), nullable=True))
    op.add_column('test_results', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'image_path')
    op.drop_column('test_results', 'note')
    # ### end Alembic commands ### 