"""Auto-generated migration

Revision ID: 774f1da2cf20
Revises: e2c5b2b2066e
Create Date: 2025-08-22 18:28:24.429106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774f1da2cf20'
down_revision = 'e2c5b2b2066e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 