"""Auto-generated migration

Revision ID: 7c3866a81820
Revises: 886f54aa575c
Create Date: 2026-02-05 18:14:41.278447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3866a81820'
down_revision = '886f54aa575c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 