"""Auto-generated migration

Revision ID: 7dbbf6fe9fa0
Revises: d7cb9a699137
Create Date: 2025-07-15 00:12:20.560992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbbf6fe9fa0'
down_revision = 'd7cb9a699137'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('test_results', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('test_results', 'image')
    # ### end Alembic commands ### 