"""Auto-generated migration

Revision ID: 7de4cd718fe5
Revises: c13de534672f
Create Date: 2025-08-23 00:20:56.247962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de4cd718fe5'
down_revision = 'c13de534672f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 