"""Auto-generated migration

Revision ID: 7e823c9c69e7
Revises: a4b1d0ccfc84
Create Date: 2026-04-27 12:14:48.589190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e823c9c69e7'
down_revision = 'a4b1d0ccfc84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 