"""Auto-generated migration

Revision ID: 80a2599b03ee
Revises: 0b6aa424b986
Create Date: 2025-07-15 18:15:34.369392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a2599b03ee'
down_revision = '0b6aa424b986'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 