"""Auto-generated migration

Revision ID: 835e6e4f771b
Revises: d884bb525d71
Create Date: 2025-08-23 00:20:03.881821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835e6e4f771b'
down_revision = 'd884bb525d71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 