"""Schema update preserving existing data

Revision ID: 835f141d7618
Revises: 
Create Date: 2025-08-22 18:07:49.125062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835f141d7618'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_parents_id'), 'project_parents', ['id'], unique=False)
    op.add_column('projects', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'project_parents', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'parent_id')
    op.drop_index(op.f('ix_project_parents_id'), table_name='project_parents')
    op.drop_table('project_parents')
    # ### end Alembic commands ### 