"""Auto-generated migration

Revision ID: 886f833a7856
Revises: a0e7a7baa8d2
Create Date: 2025-07-17 00:38:35.732807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886f833a7856'
down_revision = 'a0e7a7baa8d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 