"""Auto-generated migration

Revision ID: 8ac7f8e60420
Revises: 7e26b9dbe652
Create Date: 2026-02-28 16:24:55.075811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac7f8e60420'
down_revision = '7e26b9dbe652'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 