"""Auto-generated migration

Revision ID: 8e65e4094633
Revises: aa00c7b07e4a
Create Date: 2025-07-15 00:20:23.482100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e65e4094633'
down_revision = 'aa00c7b07e4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'image_path')
    op.drop_column('test_results', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('test_results', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 