"""Auto-generated migration

Revision ID: 8f284f4ce21a
Revises: d2ce735f826e
Create Date: 2026-04-22 18:19:15.261306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f284f4ce21a'
down_revision = 'd2ce735f826e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 