"""Auto-generated migration

Revision ID: 921b6f5230f5
Revises: 569d6a12589b
Create Date: 2026-03-10 18:16:38.226312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921b6f5230f5'
down_revision = '569d6a12589b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 