"""Auto-generated migration

Revision ID: 9911e7ea7594
Revises: 9f9b1ce0d8eb
Create Date: 2025-08-22 18:29:16.655551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9911e7ea7594'
down_revision = '9f9b1ce0d8eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 