"""Auto-generated migration

Revision ID: 9b3129601552
Revises: f23f746c87c5
Create Date: 2025-08-23 00:18:45.202018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3129601552'
down_revision = 'f23f746c87c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 