"""Auto-generated migration

Revision ID: 9be0e2367bbb
Revises: f126eea1e6a7
Create Date: 2025-08-23 00:19:37.846246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be0e2367bbb'
down_revision = 'f126eea1e6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 