"""Auto-generated migration

Revision ID: 9f02a9af0fa8
Revises: f6acd7d0a7bc
Create Date: 2026-02-28 16:45:13.343589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f02a9af0fa8'
down_revision = 'f6acd7d0a7bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 