"""Auto-generated migration

Revision ID: 9f9b1ce0d8eb
Revises: 242214557367
Create Date: 2025-08-22 18:29:03.517887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9b1ce0d8eb'
down_revision = '242214557367'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 