"""Auto-generated migration

Revision ID: a0e7a7baa8d2
Revises: 80a2599b03ee
Create Date: 2025-07-15 22:37:53.583632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e7a7baa8d2'
down_revision = '80a2599b03ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 