"""Auto-generated migration

Revision ID: a19536f5ee80
Revises: 52b449cbc56e
Create Date: 2026-05-29 14:48:54.822519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19536f5ee80'
down_revision = '52b449cbc56e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 