"""Auto-generated migration

Revision ID: a4b1d0ccfc84
Revises: 8f284f4ce21a
Create Date: 2026-04-22 18:44:13.925090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b1d0ccfc84'
down_revision = '8f284f4ce21a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 