"""Auto-generated migration

Revision ID: a7efb91b6d9f
Revises: cb814150eae2
Create Date: 2025-08-22 18:27:31.800889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7efb91b6d9f'
down_revision = 'cb814150eae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 