"""Auto-generated migration

Revision ID: aa00c7b07e4a
Revises: 7dbbf6fe9fa0
Create Date: 2025-07-15 00:14:37.369073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa00c7b07e4a'
down_revision = '7dbbf6fe9fa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('test_results', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('test_results', 'image_path')
    # ### end Alembic commands ### 