"""Auto-generated migration

Revision ID: b1c6dc01ebb2
Revises: e24b53a1b69d
Create Date: 2025-08-23 23:44:37.682149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c6dc01ebb2'
down_revision = 'e24b53a1b69d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 