"""Auto-generated migration

Revision ID: b7eacff2a6d4
Revises: bfc4d11fc982
Create Date: 2025-08-23 00:23:33.469722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7eacff2a6d4'
down_revision = 'bfc4d11fc982'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 