"""Auto-generated migration

Revision ID: bf010058b9bd
Revises: 9b3129601552
Create Date: 2025-08-23 00:18:58.377429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf010058b9bd'
down_revision = '9b3129601552'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 