"""Auto-generated migration

Revision ID: bfc4d11fc982
Revises: 7de4cd718fe5
Create Date: 2025-08-23 00:22:24.765302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc4d11fc982'
down_revision = '7de4cd718fe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 