"""Auto-generated migration

Revision ID: bfe0ab6f0229
Revises: 3667e09d6df8
Create Date: 2025-08-22 22:55:01.239152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe0ab6f0229'
down_revision = '3667e09d6df8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 