"""Auto-generated migration

Revision ID: c089b1db81c6
Revises: 886f833a7856
Create Date: 2025-07-17 01:10:06.818591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c089b1db81c6'
down_revision = '886f833a7856'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 