"""Auto-generated migration

Revision ID: c13de534672f
Revises: 59bd1fa882b3
Create Date: 2025-08-23 00:20:43.256793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13de534672f'
down_revision = '59bd1fa882b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 