"""Auto-generated migration

Revision ID: c26b30a44bbe
Revises: a7efb91b6d9f
Create Date: 2025-08-22 18:27:44.957423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26b30a44bbe'
down_revision = 'a7efb91b6d9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 