"""M2 — the sync outbox, its per-attempt state, and the fencing token

Revision ID: c4e1f8a92b07
Revises: b7c2e9a41d38
Create Date: 2026-09-06

Week 2 / M2 of the LabOS <-> Airtable integration (Epic IFET-32). Creates the
three tables the transactional outbox needs, implementing write contract §7 and
§7.1 in the database.

    !! THESE TABLES HAD NO MIGRATION AT ALL !!

    `sync_outbox`, `sync_attempt_state` and `sync_state` were declared as
    SQLAlchemy models in `app/sync/` at d61f6f5 and never given DDL. The
    committed outbox could therefore never have been deployed: `app/sync` is
    unwired, so nothing ever tried to query a table that did not exist.

    Worse, the only mechanism that *would* have created them is the
    `autogenerate` call in startup.sh - the same mechanism that produced 28
    empty no-op revisions on the node and kept the migration chain off this
    repository entirely. Had `app/sync` been wired before this file existed,
    the outbox schema would have arrived as an autogenerated revision existing
    on exactly one machine. This migration is what stops that happening.

`down_revision` is `b7c2e9a41d38` (P1). Production is still at `3a65a83e0463`,
so P1 and this revision apply as **one ordered upgrade** rather than as a
deployment and a follow-up. The head check in P1's docstring applies verbatim
and applies to this file too: confirm `SELECT * FROM alembic_version;` before
deploying, because until the startup.sh change ships every container restart
still moves the node's head.

Three properties, matching P1's:

1.  **Purely additive.** Three new tables and nothing else. No existing table is
    touched, so the running application is unaffected and a rollback is a table
    drop rather than a data-recovery exercise.

2.  **`owner_epoch` is created NOT NULL with a server default of 0**, so the
    fencing token exists from the first row and no code path has to cope with a
    NULL epoch. It is created here rather than added later precisely so there is
    never a window in which entries can be claimed without one.

3.  **The unique constraint on `(attempt_id, attempt_seq)` is the FIFO
    invariant**, enforced by the database. `enqueue()` allocates against it with
    a savepoint and a bounded retry, so a lost race rolls back one insert
    instead of the caller's whole transaction. Dropping this constraint would
    not "fix" a collision - it would let two phases of one attempt silently
    swap delivery order, which is how Airtable ends up holding a verdict with no
    measurements behind it.
"""

from alembic import op
import sqlalchemy as sa

revision = 'c4e1f8a92b07'
down_revision = 'b7c2e9a41d38'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "sync_outbox",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        # The FIFO key, and the merge key Airtable upserts on.
        sa.Column("attempt_id", sa.String(), nullable=False),
        sa.Column("attempt_seq", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(), nullable=False, server_default="pending"),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        # The fencing token. See property 2 above.
        sa.Column("owner_epoch", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.UniqueConstraint("attempt_id", "attempt_seq", name="uq_outbox_attempt_seq"),
    )
    op.create_index("ix_sync_outbox_id", "sync_outbox", ["id"])
    op.create_index("ix_sync_outbox_attempt_id", "sync_outbox", ["attempt_id"])
    op.create_index("ix_sync_outbox_state", "sync_outbox", ["state"])
    # The claim query's access path: open entries, grouped per attempt to find
    # each queue's head. Without it, every worker cycle sequentially scans the
    # whole outbox including everything already delivered.
    op.create_index("ix_sync_outbox_state_attempt_seq", "sync_outbox",
                    ["state", "attempt_id", "attempt_seq"])

    op.create_table(
        "sync_attempt_state",
        # Deliberately outlives the entries: once every entry for an attempt is
        # done we still need to know what Airtable holds, so a late duplicate is
        # recognised as superseded rather than replayed.
        sa.Column("attempt_id", sa.String(), primary_key=True, nullable=False),
        sa.Column("delivered_seq", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("delivered_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("airtable_record_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP")),
    )

    op.create_table(
        "sync_state",
        # Singleton row, id 1.
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("worker_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_push_ok_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_push_error", sa.Text(), nullable=True),
        sa.Column("last_push_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_pull_ok_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_pull_error", sa.Text(), nullable=True),
        sa.Column("last_pull_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("enabled", sa.String(), nullable=True),
    )


def downgrade():
    # Additive, so the rollback is three drops. Nothing else was touched, and no
    # existing row was modified, so this restores the pre-M2 schema exactly.
    op.drop_table("sync_state")
    op.drop_table("sync_attempt_state")
    op.drop_index("ix_sync_outbox_state_attempt_seq", table_name="sync_outbox")
    op.drop_index("ix_sync_outbox_state", table_name="sync_outbox")
    op.drop_index("ix_sync_outbox_attempt_id", table_name="sync_outbox")
    op.drop_index("ix_sync_outbox_id", table_name="sync_outbox")
    op.drop_table("sync_outbox")
