"""Auto-generated migration

Revision ID: c5bf54a6039d
Revises: b7eacff2a6d4
Create Date: 2025-08-23 00:25:46.266897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bf54a6039d'
down_revision = 'b7eacff2a6d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 