"""Auto-generated migration

Revision ID: cb814150eae2
Revises: 835f141d7618
Create Date: 2025-08-22 18:27:18.696534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb814150eae2'
down_revision = '835f141d7618'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 