"""Auto-generated migration

Revision ID: d11e80d5b324
Revises: 4fc870f689e8
Create Date: 2025-08-26 16:53:59.385440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11e80d5b324'
down_revision = '4fc870f689e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 