"""Auto-generated migration

Revision ID: d2ce735f826e
Revises: f9d7cd34992a
Create Date: 2026-04-22 15:10:02.334257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ce735f826e'
down_revision = 'f9d7cd34992a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 