"""Auto-generated migration

Revision ID: d39f83a72b51
Revises: 06ae0a2719a5
Create Date: 2025-08-22 23:43:05.259217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39f83a72b51'
down_revision = '06ae0a2719a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 