"""Auto-generated migration

Revision ID: d500ef66e207
Revises: f69e1eff0c40
Create Date: 2026-04-21 19:31:36.005370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd500ef66e207'
down_revision = 'f69e1eff0c40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 