"""Auto-generated migration

Revision ID: d7cb9a699137
Revises: 
Create Date: 2025-07-15 00:09:35.458383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cb9a699137'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('turbo_mode', sa.Boolean(), nullable=False),
    sa.Column('turbo_slave', sa.Boolean(), nullable=False),
    sa.Column('turbo_charger', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turbo_charger'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_number', sa.Integer(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_table('deflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deflection_gauge', sa.String(), nullable=False),
    sa.Column('max_deflection', sa.Float(), nullable=False),
    sa.Column('permanent_deflection', sa.Float(), nullable=False),
    sa.Column('recovery', sa.Float(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deflections_id'), 'deflections', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('inward_design_pressure', sa.Float(), nullable=False),
    sa.Column('outward_design_pressure', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('cyclic_tests',
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('cycles', sa.Integer(), nullable=False),
    sa.Column('low_pressure', sa.Float(), nullable=False),
    sa.Column('high_pressure', sa.Float(), nullable=False),
    sa.Column('resume', sa.Boolean(), nullable=False),
    sa.Column('current_cycle', sa.Integer(), nullable=False),
    sa.Column('preset', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cyclic_tests_id'), 'cyclic_tests', ['id'], unique=False)
    op.create_table('infiltration_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('leakage', sa.Float(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infiltration_tests_id'), 'infiltration_tests', ['id'], unique=False)
    op.create_table('missile_impact_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('missile', sa.String(), nullable=False),
    sa.Column('missile_weight', sa.Float(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missile_impact_tests_id'), 'missile_impact_tests', ['id'], unique=False)
    op.create_table('static_tests',
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('pressure_factor', sa.String(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('preset', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_tests_id'), 'static_tests', ['id'], unique=False)
    op.create_table('cyclic_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cyclic_test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cyclic_test_id'], ['cyclic_tests.id'], ),
    sa.ForeignKeyConstraint(['id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cyclic_test_results_id'), 'cyclic_test_results', ['id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('missile_impact_test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['missile_impact_test_id'], ['missile_impact_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_id'), 'shots', ['id'], unique=False)
    op.create_table('static_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('static_test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['test_results.id'], ),
    sa.ForeignKeyConstraint(['static_test_id'], ['static_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_test_results_id'), 'static_test_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_static_test_results_id'), table_name='static_test_results')
    op.drop_table('static_test_results')
    op.drop_index(op.f('ix_shots_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_cyclic_test_results_id'), table_name='cyclic_test_results')
    op.drop_table('cyclic_test_results')
    op.drop_index(op.f('ix_static_tests_id'), table_name='static_tests')
    op.drop_table('static_tests')
    op.drop_index(op.f('ix_missile_impact_tests_id'), table_name='missile_impact_tests')
    op.drop_table('missile_impact_tests')
    op.drop_index(op.f('ix_infiltration_tests_id'), table_name='infiltration_tests')
    op.drop_table('infiltration_tests')
    op.drop_index(op.f('ix_cyclic_tests_id'), table_name='cyclic_tests')
    op.drop_table('cyclic_tests')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_deflections_id'), table_name='deflections')
    op.drop_table('deflections')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ### 