"""Auto-generated migration

Revision ID: d884bb525d71
Revises: 9be0e2367bbb
Create Date: 2025-08-23 00:19:50.922021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd884bb525d71'
down_revision = '9be0e2367bbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 