"""Auto-generated migration

Revision ID: d91ea44974fb
Revises: 9911e7ea7594
Create Date: 2025-08-22 18:30:48.062331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91ea44974fb'
down_revision = '9911e7ea7594'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 