"""Auto-generated migration

Revision ID: e24b53a1b69d
Revises: 5b949d1fd354
Create Date: 2025-08-23 23:38:33.610405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24b53a1b69d'
down_revision = '5b949d1fd354'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 