"""Auto-generated migration

Revision ID: e2c5b2b2066e
Revises: 4dd8c0d0e3ac
Create Date: 2025-08-22 18:28:10.897008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c5b2b2066e'
down_revision = '4dd8c0d0e3ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 