"""Auto-generated migration

Revision ID: e3aabb037243
Revises: 5299a866852e
Create Date: 2026-06-30 13:12:57.174671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3aabb037243'
down_revision = '5299a866852e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 