"""Auto-generated migration

Revision ID: e71f57311002
Revises: 835e6e4f771b
Create Date: 2025-08-23 00:20:17.069623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71f57311002'
down_revision = '835e6e4f771b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 