"""Auto-generated migration

Revision ID: eb03d573f874
Revises: 348d5245e1e7
Create Date: 2026-02-28 02:25:10.922254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb03d573f874'
down_revision = '348d5245e1e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 