"""Auto-generated migration

Revision ID: ed02840fb51f
Revises: 014591936c07
Create Date: 2025-08-22 23:44:12.603522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed02840fb51f'
down_revision = '014591936c07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 