"""Auto-generated migration

Revision ID: eed040329fc8
Revises: 9f02a9af0fa8
Create Date: 2026-02-28 16:47:25.622043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed040329fc8'
down_revision = '9f02a9af0fa8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 