"""Auto-generated migration

Revision ID: f126eea1e6a7
Revises: 0a1ea4a4d75e
Create Date: 2025-08-23 00:19:24.393730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f126eea1e6a7'
down_revision = '0a1ea4a4d75e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 