"""Auto-generated migration

Revision ID: f23f746c87c5
Revises: ed02840fb51f
Create Date: 2025-08-22 23:44:26.642923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23f746c87c5'
down_revision = 'ed02840fb51f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 