"""Auto-generated migration

Revision ID: f69e1eff0c40
Revises: 921b6f5230f5
Create Date: 2026-04-21 16:20:54.253927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69e1eff0c40'
down_revision = '921b6f5230f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 