"""Auto-generated migration

Revision ID: f6acd7d0a7bc
Revises: 8ac7f8e60420
Create Date: 2026-02-28 16:42:35.992445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6acd7d0a7bc'
down_revision = '8ac7f8e60420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 