"""Auto-generated migration

Revision ID: f9a994aa16c3
Revises: d91ea44974fb
Create Date: 2025-08-22 18:37:30.502663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a994aa16c3'
down_revision = 'd91ea44974fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 