"""Auto-generated migration

Revision ID: f9d7cd34992a
Revises: d500ef66e207
Create Date: 2026-04-22 13:34:53.279148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d7cd34992a'
down_revision = 'd500ef66e207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 